<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Pixnop.Atlas.XUnit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="VintagestoryServer">
      <HintPath>$(VINTAGE_STORY)/VintagestoryServer.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <ProjectReference Include="../../src/PapermakingPapyrus/PapermakingPapyrus.csproj" AtlasMod="true" />
  </ItemGroup>
</Project>
